/* seed.js —— 种子演示数据（纯数据、无逻辑）
 * 首次打开时由 js/api.js 灌入 localStorage，方便直接体验浏览与搜索。
 * 全部为「进行中(active)」条目，publisher 留空（不属于任何本机匿名 uid）。
 */
(function (root) {
  'use strict';

  root.SEED_ITEMS = [
    {
      "id": "seed-01",
      "type": "found",
      "title": "捡到一张校园卡",
      "category": "证件卡类",
      "location": "三教 201 门口",
      "time": "2026-10-02 09:30",
      "description": "今天早上在三教 201 门口的桌子上捡到一张校园卡，卡面贴有一张卡通贴纸。请失主联系我核对姓名。",
      "contact": "微信：lost_found_01",
      "image": "",
      "status": "active",
      "publisher": "",
      "publisherName": "李同学",
      "dept": "计算机学院",
      "createdAt": 1790899200000
    },
    {
      "id": "seed-02",
      "type": "found",
      "title": "捡到一把黑色雨伞",
      "category": "雨伞",
      "location": "图书馆三楼",
      "time": "2026-10-01 16:05",
      "description": "图书馆三楼靠窗座位边捡到一把黑色折叠伞，伞柄有蓝色挂绳。",
      "contact": "微信：umbrella_finder",
      "image": "",
      "status": "active",
      "publisher": "",
      "publisherName": "张同学",
      "dept": "外国语学院",
      "createdAt": 1790895000000
    },
    {
      "id": "seed-03",
      "type": "lost",
      "title": "丢失一只白色蓝牙耳机",
      "category": "耳机",
      "location": "体育馆羽毛球场",
      "time": "2026-09-21 20:10",
      "description": "运动结束后发现一只白色蓝牙耳机不见了，对我很重要，捡到必有重谢。",
      "contact": "电话：138****5678",
      "image": "",
      "status": "active",
      "publisher": "",
      "publisherName": "王同学",
      "dept": "软件学院",
      "createdAt": 1790880000000
    },
    {
      "id": "seed-04",
      "type": "found",
      "title": "捡到一张学生证",
      "category": "证件卡类",
      "location": "教学楼 B 区 302",
      "time": "2026-10-01 15:20",
      "description": "第三节课下课后在抽屉里捡到一张学生证，已放到讲台。",
      "contact": "微信：help_wang",
      "image": "",
      "status": "active",
      "publisher": "",
      "publisherName": "刘同学",
      "dept": "机械学院",
      "createdAt": 1790870000000
    },
    {
      "id": "seed-05",
      "type": "lost",
      "title": "丢失一串宿舍钥匙",
      "category": "钥匙",
      "location": "一食堂二楼",
      "time": "2026-10-01 18:20",
      "description": "一串三把钥匙，带一个灰色小熊挂坠，很急，捡到请联系我。",
      "contact": "微信：key_seeker",
      "image": "",
      "status": "active",
      "publisher": "",
      "publisherName": "陈同学",
      "dept": "经济学院",
      "createdAt": 1790860000000
    },
    {
      "id": "seed-06",
      "type": "found",
      "title": "捡到一个保温水杯",
      "category": "水杯",
      "location": "操场看台",
      "time": "2026-10-02 08:15",
      "description": "早上在操场看台拾到一个银色保温杯，杯底贴有姓名贴。",
      "contact": "微信：cup_owner_help",
      "image": "",
      "status": "active",
      "publisher": "",
      "publisherName": "赵同学",
      "dept": "物理学院",
      "createdAt": 1790700000000
    },
    {
      "id": "seed-07",
      "type": "lost",
      "title": "丢失《数据结构》教材",
      "category": "图书",
      "location": "一教 105",
      "time": "2026-10-01 10:40",
      "description": "蓝色封面的《数据结构》，扉页写有名字，忘在教室了。",
      "contact": "微信：book_lost",
      "image": "",
      "status": "active",
      "publisher": "",
      "publisherName": "孙同学",
      "dept": "文学院",
      "createdAt": 1790600000000
    },
    {
      "id": "seed-08",
      "type": "found",
      "title": "捡到一个蓝色水杯",
      "category": "水杯",
      "location": "第一食堂门口",
      "time": "2026-09-29 13:00",
      "description": "在第一食堂门口捡到一个蓝色运动水杯，杯身有划痕，请失主说明特征来认领。",
      "contact": "微信：blue_cup",
      "image": "",
      "status": "active",
      "publisher": "",
      "publisherName": "周同学",
      "dept": "化工学院",
      "createdAt": 1790500000000
    },
    {
      "id": "seed-09",
      "type": "lost",
      "title": "丢失一张校园卡",
      "category": "证件卡类",
      "location": "图书馆",
      "time": "2026-09-28 10:00",
      "description": "昨天在图书馆看书时校园卡不小心掉了，卡号尾号 027，捡到请联系我，谢谢。",
      "contact": "微信：card_027",
      "image": "",
      "status": "active",
      "publisher": "",
      "publisherName": "吴同学",
      "dept": "数学学院",
      "createdAt": 1790400000000
    },
    {
      "id": "seed-10",
      "type": "found",
      "title": "捡到一副黑框眼镜",
      "category": "其他",
      "location": "二教 305",
      "time": "2026-09-27 21:15",
      "description": "晚自习后在二教 305 第三排捡到一副黑框眼镜，放在讲台抽屉里了。",
      "contact": "微信：glasses_finder",
      "image": "",
      "status": "active",
      "publisher": "",
      "publisherName": "郑同学",
      "dept": "信息学院",
      "createdAt": 1790300000000
    }
  ];
})(typeof window !== 'undefined' ? window : this);
